name: Print README
on: push  
jobs:
  print-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print README
        run: cat README.md