# name: Cowsay
# on: push
# jobs:
#     Ascii_job:

#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout repo
#               uses: actions/checkout@v4

#             - name: install cowsay program
#               run: sudo apt-get install cowsay -y

#             - name: Execute cowsay CMD
#               run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt

#             - name: Test File Exists
#               run: grep -i "dragon" dragon.txt

#             - name: Read File
#               run: cat dragon.txt

#             - name: checkout repo files
#               run: ls


# name: Solar System WorkFlow

# on:
#     workflow_dispatch:
#     push:
#         branches:
#             - main
#             - 'feature/*'

# env:
#     MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
#     MONGO_USERNAME: ${{secrets.DOCKER_USERNAME}}
#     MONGO_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

# jobs:

#     unit-testing:
#         name: Unit Testing
#         strategy: 
#             matrix: 
#                 nodejs_version: [18,19,20]
#                 operating_system: [unbuntu-latst, macos-latest]
#                 exclude:
#                     - nodejs_version: 18
#                       operating_system: macos-latest
                      
#         runs-on: ${{ matrix.operating_system }}
#         steps: 

#             - name: checkout Repository
#               uses: actions/checkout@v4

#             - name: Setup NodeJS Version - ${{matrix.nodejs_version}}
#               uses: actions/setup-node@v3
#               with:
#                 node-version: ${{matrix.nodejs_version}}

#             - name: Install Dependencies
#               run: npm install

#             - name: Unit Testing 
#               run: npm test

#             - name: Archive test result 
#               uses : actions/upload-artifact@v3
#               with:
#                 name: Mocha-Test-Result
#                 path: test-results.xml

